---
- hosts: jenkins_server
  become_user: root
  vars_files:
    - ./group_vars/treasurehunt-release.vault
    - ./group_vars/treasurehunt-release.yml
  roles: 
    - ansible
    - treasurehunt-release
