- name: Adding Jenking Repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/
    mode: '0755'

- rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

- name: Install jenkins
  yum:
    name: jenkins
    state: latest

- name: Install java
  yum:
    name: java
    state: latest

- name: Start jenkins on startup
  service: 
    name: jenkins
    enabled: yes
    state: started
