---
- name: Create ansible group
  group:
    name: ansible
    state: present
  when:
    - "'ansible' in groups"

- name: Create ansible user
  user:
    name: ansible
    group: ansible
    home: /home/ansible

- name: Check installed packages
  package_facts:
    manager: auto

- name: Add EPEL repository
  yum: 
    name: epel-release
    state: present
  when: "'epel-release' not in ansible_facts.packages"

- name: Install pip
  yum:
    name: python-pip
    state: present
  when: "'python2-pip' not in ansible_facts.packages"

- name: Install ansible
  command: pip install ansible

- name: Install boto and botocore
  command: pip install boto3 botocore
