---
- name: Create group
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - bnicolas
    - mareal
    - cleoparte
    - dpampola
    - eroxas
    - abarrientos
    - dalava
    - fbravo

- name: Create user
  user:
    name: "{{ item }}"
    group: "{{ item }}"
    shell: /bin/bash
  with_items:
    - bnicolas
    - mareal
    - cleoparte
    - dpampola
    - eroxas
    - abarrientos
    - dalava
    - fbravo

- name: Create .ssh directory
  file:
    path: /home/{{ item }}/.ssh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
    state: directory
  with_items:
    - bnicolas
    - mareal
    - cleoparte
    - dpampola
    - eroxas
    - abarrientos
    - dalava
    - fbravo

- name: Create .ssh/authorized_keys file
  file:
    path: /home/{{ item }}/.ssh/authorized_keys
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
    state: touch
  with_items:
    - bnicolas
    - mareal
    - cleoparte
    - dpampola
    - eroxas
    - abarrientos
    - dalava
    - fbravo

- name: Add key in their own .ssh/authorized_keys
  shell: echo "{{ item.key }}" > /home/{{ item.user }}/.ssh/authorized_keys
  with_items:
    - { "user": "bnicolas", "key": "{{ lookup('vars', 'vault_bnicolas') }}" }
    - { "user": "mareal", "key": "{{ lookup('vars', 'vault_mareal') }}" }
    - { "user": "cleoparte", "key": "{{ lookup('vars', 'vault_cleoparte') }}" }
    - { "user": "dpampola", "key": "{{ lookup('vars', 'vault_dpampola') }}" }
    - { "user": "eroxas", "key": "{{ lookup('vars', 'vault_eroxas') }}" }
    - { "user": "abarrientos", "key": "{{ lookup('vars', 'vault_abarrientos') }}" }
    - { "user": "dalava", "key": "{{ lookup('vars', 'vault_dalava') }}" }
    - { "user": "fbravo", "key": "{{ lookup('vars', 'vault_fbravo') }}" }

- name: Remove users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
    - hyap
